version: '3.8'

services:
  app:
    build: .
    container_name: chat-app
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=localhost
      - DATABASE_PORT=9000
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=13082004
      - DATABASE_NAME=testapo
    depends_on:
      - db
    networks:
      - chat-network

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=13082004
      - POSTGRES_DB=testapo
    ports:
      - "9000:9000"
    networks:
      - chat-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  chat-network:
    driver: bridge

volumes:
  postgres-data:
